### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by SaiWannaAung1** [PaulGwamanda/Pix2code-Screenshot-to-code-dataset-builder#1]
There has occur Parsing Error when I predict image to code and that is shown in below figure. 

![Capture](https://user-images.githubusercontent.com/45900997/175572357-33845362-378a-42c2-8e01-348c2fb91829.PNG)

This image is predict result.

![Capture](https://user-images.githubusercontent.com/45900997/175573530-fcb6f697-1f03-432c-9693-4e3c4c25da3c.PNG)

**Comment by PaulGwamanda** [comment]
The model needs more training epochs
